<?php
define("DB_DSN", "mysql:host=localhost;port=8889;dbname=ztmfs");
define("DB_USERNAME", "root");
define("DB_PASSWORD", "root");
define("EMAIL_SENDER", "info@zoetermeerfonds.nl");
define("ADMINISTRATOR", "admin");
define("ADMIN_PASSW", "admin");
/*
define("DB_DSN", "mysql:host=localhost;dbname=prohuyg144_biz2d");
define("DB_USERNAME", "prohuyg144_jangg"); //username of the database
define("DB_PASSWORD", "Opgep1st"); //password of the database
define("EMAIL_SENDER", "jan@bizkwadraat.nl");
define("ADMINISTRATOR", "admin");
define("ADMIN_PASSW", "admin");
*/


?>