	<meta property="fb:app_id"			   content="346042092413420" />
	<meta property="og:url"                content="https://www.zoetermeerfonds.nl/" />
	<meta property="og:author"             content="Zoetermeerfonds" />
	<meta property="og:type"               content="article" />
	<meta property="og:title"              content="Maak meer mogelijk met het Zoetermeerfonds" />
	<meta property="og:description"        content="Het Zoetermeerfonds ondersteunt initiatieven van inwoners van Zoetermeer die zelf of samen met andere inwoners willen bijdragen aan een betere lokale samenleving." />
	<meta property="og:image"              content="https://www.zoetermeerfonds.nl/img/logos/zflogo_fb.jpg" />

<!--
	<meta property="fb:app_id"			   content="346042092413420" />
	<meta property="og:url"                content="http://www.zoetermeerfonds.nl#nieuws/" />
	<meta property="og:author"             content="Zoetermeerfonds" />
	<meta property="og:type"               content="article" />
	<meta property="og:title"              content="Persbericht Zoetermeerfonds 26 oktober" />
	<meta property="og:description"        content="Bekendmaking van de start van het Zoetermeerfonds per 1 november a.s." />
	<meta property="og:image"              content="https://www.zoetermeerfonds.nl/img/persbericht1.jpg" /> 
-->

<!--
	<meta property="fb:app_id"			   content="346042092413420" />
	<meta property="og:url"                content="https://www.zoetermeerfonds.nl/" />
	<meta property="og:author"             content="Zoetermeerfonds" />
	<meta property="og:type"               content="article" />
	<meta property="og:title"              content="Het Zoetermeerfonds opent zijn deuren!" />
	<meta property="og:description"        content="Vanaf dinsdag 1 november kunnen inwoners van Zoetermeer hun plannen voor de stad indienen en een aanvraag doen voor een financiële bijdrage." />
	<meta property="og:image"              content="https://www.zoetermeerfonds.nl/img/zfopening.jpg" /> 
-->
