<!------            F O O T E R ------------->    
	<div id="footer1">
	    <div class="container">
			<div class="row">
	            <div class="col-md-4">
		            <ul>
		            <li class="first-p">Onze partners</li>
		            <li><hr></li>
	                <li><a href="http://www.lokalefondsen.nl" target="_blank">Lokale Fondsen Nederland</a></li>
					<li><a href="http://www.fonds1818.nl" target="_blank">Fonds 1818</a></li>
	                <li><a href="http://www.zoetermeer.nl" target="_blank">Gemeente Zoetermeer</a></li>
	                <li><a href="http://www.bizkwadraat.nl" target="_blank">BizKwadraat</a></li>
		            </ul>
	            </div>
	            <div class="col-md-4">
		            <ul>
		            <li class="first-p">Contactgegevens</li>
		            <li><hr></li>
                    <li>Stichting Zoetermeerfonds</li>
                    <li>Postadres: Giekwerf 19, 2725 DV Zoetermeer</li>
	                <li>Emailadres: <a href="mailto:info@zoetermeerfonds.nl">info@zoetermeerfonds.nl</a></li>
	                <li>Telefoonnummer: 06-24843535</li>
                    </ul>
	            </div>
	            <div class="col-md-4">
		            <ul>
		            <li class="first-p">Overige informatie</li>
		            <li><hr></li>
		            <li>KvK: 66635055</li>
		            <li>RSIN: 8566.39.989</li>
		            <li>Rekeningnummer: NL 98 RABO 0311 7524 11</li>
		            <ul>		            
	            </div>
			</div>
	    </div>
	</div>
	<div id="footer2">
	    <div class="container">
	        <div class="row">
	            <div class="col-md-4">
	                <p class="list-inline copyright">&copy 2018 Het Zoetermeer&shy;fonds</p>
	            </div>
	            <div class="col-md-4">
	                <ul class="list-inline social-buttons">
	                    <li><a href="http://www.twitter.com/zoetermeerfonds" target="_blank"><i class="fa fa-twitter"></i></a>
	                    </li>
	                    <li><a href="http://www.facebook.com/zoetermeerfonds" target="_blank"><i class="fa fa-facebook"></i></a>
	                    </li>
	                    <li><a href="https://www.linkedin.com/company/stichting-zoetermeerfonds" target="_blank"><i class="fa fa-linkedin"></i></a>
	                    </li>
	                </ul>
	            </div>
	            <div class="col-md-4">
	                <ul class="quicklinks">
	                    <li><a href="disclaimer.php#disclaimer">Disclaimer</a>
	                    </li>
	                    <li><a href="voorwaarden.php#algemenevoorwaarden">Algemene voorwaarden</a>
	                    </li>
	                    <li><a href="cookiepolicy.php#cookies">Cookies en privacy</a>
	                    </li>
	                    <li><a href="beheer/index.php">Inloggen</a>
	                    </li>
	                    <br/><br/>
					</ul>
	            </div>
	        </div>
	    </div>
	</div>
<!------  einde     F O O T E R ------------->    

