    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Het Zoetermeerfonds is het lokale fonds in Zoetermeer dat maatschappelijke initiatieven steunt.">
<!--     <meta name="author" content="ProHunter"> -->
    <meta name="keywords" content="Zoetermeer, Zoetermeerfonds, maatschappelijke initiatieven, burgerinitiatief, burgerinitiatieven, lokaal fonds, lokale fondsen">
    <meta name="robots" content="index, follow">

	<?php // include_once ('FB_OpenGraph.inc'); ?>

	<link rel="shortcut icon" type="image/png" href="img/favicon_zf.png"/>
	
    <title>Het Zoetermeerfonds</title>

    <!-- JQuery -->

	<script   src="https://code.jquery.com/jquery-1.12.4.js"   integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="   crossorigin="anonymous"></script>

    <!-- Facebook pixelcode -->
    <?php include_once ('includes/fb_pixelcode.inc'); ?>
	
    <!-- Bootstrap Core CSS -->
<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <!-- Custom CSS -->
    <link href="css/agency.css" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href='font-awesome/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>

    <script src='https://www.google.com/recaptcha/api.js'></script>


