    <!-- Header -->
    <header>
        <div class="container doverlay">
			<div class="row">
				<div class="col-sm-4">
					<a href="questionnaire.php#questionnaire">
        				<div class="post-it pi-l hidden-sm hidden-xs" style="margin: 0 auto; top: 100px; font-size: 1.5em; line-height: 160%; cursor: pointer;">
    					Niet zeker of je in aanmerking komt voor een bijdrage? Klik hier voor een korte quick-scan, vul 'm in en je weet meer
    					</div>
					</a>
				</div>
				<div class="col-sm-4">
                <div class="intro-lead-in">Welkom bij het <img src="../img/logos/zflogo_100.png" alt="zflogo_100" width="70%" class="img-responsive img-centered" /></div>
				</div>
				<div class="col-sm-4">
					<a href="aanvform.php#aanvform">
        				<div class="post-it pi-r hidden-sm hidden-xs" style="margin: 0 auto; top: 100px; font-size: 1.5em; line-height: 160%; cursor: pointer;">
    					Eerste hulp bij aanvraag voor je maatschappelijk initiatief. Jan Geerdes, de initiatievenmakelaar, is ieder dinsdagmiddag van half 2 tot half 5 aanwezig op het Stadhuis-Forum van Zoetermeer. Kom langs op het plein Educatie & Ontwikkeling en stel je vragen!
    					</div>
					</a>
				</div>
			</div>
            <div class="intro-text">
                <div class="intro-heading">#Zo doen we dat in deze stad.</div>
	            <div class="intro-lead-in">Lokale initiatieven verdienen steun.</div>

                <a href="index.php#newsletter" class="btn btn-xl">Blijf op de hoogte,<br/>geef je emailadres door</a>
            </div>
        </div>
    </header>
