    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigatie</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
<!--                 <a class="navbar-brand page-scroll" href="index.php#page-top">Het Zoetermeerfonds</a> -->
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="page-scroll" href="index.php">Home</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Informatie <span class="caret"></span></a>
	                    <ul class="dropdown-menu">
		                    <li><a class="page-scroll" href="index.php#watis">Wat is het Zoetermeerfonds?</a></li>
		                    <li><a class="page-scroll" href="index.php#doelen">De doelen</a></li>
		                    <li><a class="page-scroll" href="index.php#initnemers">Voor initiatiefnemers</a></li>
		                    <li><a class="page-scroll" href="index.php#donateurs">Voor donateurs</a></li>
	                    </ul>
                    </li>
                    <li><a class="page-scroll" href="index.php#nieuws">Nieuws</a></li>
                    <li><a class="page-scroll" href="index.php#donateurs">Doneren</a></li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Aanvragen <span class="caret"></span></a>
	                    <ul class="dropdown-menu">
		                    <li><a class="page-scroll" href="aanvform.php#criteria">De voorwaarden</a></li>
		                    <li><a class="page-scroll" href="aanvform.php#spelregels">De spelregels</a></li>
		                    <li><a class="page-scroll" href="aanvform.php#aanvragen">Een aanvraag indienen</a></li>
		                    <li><a class="page-scroll" href="questionnaire.php#questionnaire">Doe een voorwaarden scan</a></li>
<!-- 		                    <li><a class="page-scroll" href="overz_aanvr.php#overzicht">Overzicht aanvragen</a></li> -->
	                    </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Over ons<span class="caret"></span></a>
	                    <ul class="dropdown-menu">
		                    <li><a class="page-scroll" href="contact.php#bestuur">Het bestuur</a></li>
		                    <li><a class="page-scroll" href="contact.php#partners">Onze partners</a></li>
		                    <li><a class="page-scroll" href="contact.php#contact">Contact</a></li>
		                    <li><a class="page-scroll" href="vacatures.php#vacatures">Vacatures</a></li>
		                    <li><a class="page-scroll" href="beheer/index.php">Inloggen</a></li>
	                    </ul>
                    </li>
               </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

