    <!-- subject Modals -->
    <!-- Use the modals below to showcase details about your subject projects! -->

    <!-- subject Modal 1 -->
    <div class="subject-modal modal fade" id="subjectModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Wat is een lokaal fonds en voor wie is het bedoeld?</h2>
                            <p class="item-intro text-muted"></p>
                            <img class="img-responsive img-centered" src="img/subject/fonds.jpg" width="600" alt="">
                            <h4>Wat is het?</h4>
                            <p>Een lokaal fonds is een door betrokken personen (vrijwilligers) zelfstandig geleide private stichting of organisatie, die mensen bij elkaar brengt om de leefbaarheid in de omgeving te verbeteren. Met tijd, betrokkenheid, ideeën en geld realiseert of initieert een lokaal fonds tal van uiteenlopende lokale projecten en initiatieven. Hiervoor werft een lokaal fonds inkomsten, bouwt een reserve op ten behoeve van de continuïteit en werkt zoveel mogelijk samen met partners.</p>
                            <h4>Voor wie is het?</h4>
                            <p>Het fonds is er voor alle Zoetermeerders die iets willen betekenen voor de stad. Inwoners met ideeën zijn van harte welkom om ons voor te leggen wat zij graag tot werkelijkheid zien komen, hoe zij denken dat voor elkaar te krijgen en wat zij daar voor nodig denken te hebben. Wij, van onze kant, denken graag mee en kunnen, als aan de condities wordt voldoen, een financiële bijdrage leveren om de ideeën te realiseren.</p>
                            
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subject Modal 2 -->
    <div class="subject-modal modal fade" id="subjectModal2" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <h2>Hoe dien je een aanvraag voor een bijdrage in?</h2>
                            <img class="img-responsive img-centered" src="img/subject/goeddoel.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">Een goed plan en een goed verhaal erbij zijn cruciaal.	                            
                            </h4>>
                            <p><strong>Benader ons als je een initiatief wilt opzetten of vragen hierover hebt.</strong></p>
							<p>Voor het indienen van een initiatief is een <a href="aanvform.php#aanvform"><strong>inschrijfformulier</strong></a> beschikbaar maar een aanvraag mag ook geheel vormvrij worden ingediend. Houd bij het indienen van een aanvraag wel rekening met <a href="aanvform.php#criteria"><strong>de voorwaarden</strong></a> en <a href="aanvform.php#spelregels"><strong>spelregels</strong></a>. Tip: loop de voorwaarden en spelregels puntsgewijs na bij het opstellen van je aanvraag en dien een zo compleet mogelijke aanvraag in. Hoe duidelijker en completer de aanvraag, hoe soepeler het proces zal verlopen.</p>
							
							<p>Dien een aanvraag eenvoudig in via het online formulier, met een email, of stel een vraag wanneer nodig.</p>
							
							<p>Mogelijk hebben we dan een paar vragen om tot een duidelijk beeld van uw aanvraag te komen. De bestuursleden gaan dan je aanvraag beoordelen. Het gaat dan niet alleen om geld, stel ook rustig de vragen die je initiatief beter kunnen maken.</p>
							
							<p>We denken graag mee, maar nemen je initiatief nooit over.</p>
							<p>Wij zullen zo snel mogelijk een beslissing nemen over je aanvraag. In het kort: kleine bedragen willen we binnen een maand verwerken, grotere bedragen zullen meer tijd vergen. Bij de grotere bedragen zullen namelijk ook meer mensen voor de beoordeling ingeschakeld worden. Bij grotere bedragen is co-financiering in principe een vereiste.
							</p>
							<p>Elke beslissing zullen we motiveren zodat je daarmee ook bij andere fondsen kunt aankloppen.</p>

                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subject Modal 3 -->
    <div class="subject-modal modal fade" id="subjectModal3" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Welke voorwaarden stellen we?</h2>
                            <img class="img-responsive img-centered" src="img/subject/aanvraag.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">Waar moeten het initiatief en de initiatiefnemers aan voldoen?</h4>

							<p>Hierbij de voorwaarden voor een aanvraag. 
								Als de aanvraag niet volledig is zullen wij -indien van toepassing- extra vragen stellen. Je kunt ons dus al in een vrij vroeg stadium van uw initiatief benaderen. 
								Vervolgens kunnen we samen de aanvraag samenstellen.</p>

 
							<ul>
							<li>Het initiatief komt ten goede aan Zoetermeer en/of zijn inwoners.</li>
							<li>In principe  moeten alle inwoners van Zoetermeer in de gelegenheid worden gesteld van het initiatief te profiteren.</li>
							<li>Initiatiefnemers en inwoners van Zoetermeer dienen te participeren in de uitvoering van het project. Zij werken op vrijwillige basis mee of stellen middelen ter beschikking zonder daarvoor betaald te krijgen.</li>
<!-- 							<li>Het initiatief mag geen gemeentelijk beleid doorkruisen.</li> -->
							<li>Arbeid wordt niet vergoed, tenzij aannemelijk kan worden gemaakt dat het niet door vrijwilligers verricht kan worden.</li>
							<li>De bijdrage van het Zoetermeerfonds dient significant (belangrijk) te zijn voor het slagen van het initiatief.</li>
							<li>Discriminerende activiteiten zijn niet toegestaan.</li>
							<li>Aanvragen worden ingediend voordat het initiatief is gestart. Aanvragen voor al gestarte initiatieven worden afgewezen.</li>
							<li>Co-financiering is in principe vereist, zeker bij grotere initiatieven (als de gevraagde bijdrage 2000 euro of meer bedraagt).</li>
							<li>Indiener moet een inwoner van Zoetermeer zijn of een Zoetermeerse organisatie zonder winstoogmerk.</li>
							<li>Initiatief dient geen politiek of religieus doel.</li>
							<li>Omvang van de aanvraag begint bij 100 euro.</li>
							<li>De maximale bijdrage die het Zoetermeerfonds uitkeert bedraagt <strong>5000 euro</strong>.
							<li>Voorafgaande aan een uitkering boven de 1000 euro, wordt identiteitscontrole verlangd.</li>
							<li>Na afloop ontvangt het bestuur een verslag incl. financiële verantwoording van de initiatiefnemer.</li>
							<li>Initiatiefnemers geven volledige openheid van zaken omtrent financiën, indien van gevraagd door het Zoetermeerfonds.</li>
							</ul>
							<p><a href="voorwaarden.php#algemenevoorwaarden">Hier</a> vind je de formele Algemene Voorwaarden die het Zoetermeerfonds stelt wanneer een initiatiefnemer een financiële bijdrage van het fonds ontvangt.<p>
							<p>Het Zoetermeerfonds helpt je graag om een zo goed mogelijke aanvraag in te dienen.</p>

								
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subject Modal 4 -->
    <div class="subject-modal modal fade" id="subjectModal4" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
	                        
	                        
                            <!-- Project Details Go Here -->
                            <h2>Wat zijn de spelregels?</h2>
                            <img class="img-responsive img-centered" src="img/subject/doelgroep.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">Lees ze goed, ze zijn belangrijk.</h4>
							<p>Hierbij de spelregels voor een aanvraag. Benader ons als zaken niet duidelijk zijn.</p>
							
							<ol>
								<li>Aanvrager gaat ermee akkoord dat de aanvraag, of een samenvatting hiervan, en de uiteindelijke beoordeling, openbaar worden gepubliceerd op de website.
								</li>
								<li>De uiteindelijke beoordeling is definitief, hier kan niet over worden gecorrespondeerd.
								</li>
								<li>Bij alle communicatie over de activiteit dient u de naam of het logo van het Zoetermeerfonds te vermelden.
								</li>
								<li>Initiatiefnemers blijven zelf verantwoordelijk voor de organisatie van het initiatief.
								</li>
								<li>De aanvrager dient een Zoetermeerse organisatie / vereniging of een inwoner van Zoetermeer te zijn.
								</li>
								<li>Het Zoetermeerfonds doet haar best om bij de initiatieven te helpen, maar kan nooit garanties geven voor het slagen hiervan.
								</li>
								<li>Elke poging tot ongewenste inmenging in het beoordelingsproces is niet toegestaan en zorgt ervoor dat de aanvraag wordt afgewezen.
								</li>
								<li>Door een aanvraag te doen, verklaart u zich akkoord met deze spelregels.
								</li>
							</ol>                            
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subject Modal 5 -->
    <div class="subject-modal modal fade" id="subjectModal5" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Aanvraag ingediend. Wat nu?</h2>
                            <img class="img-responsive img-centered" src="img/subject/doelgroep.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">Je moet er even bij blijven voor het beste resultaat</h4>
                            <p>Je aanvraag is ingediend, alle stukken en documenten heb je online verstuurd of misschien via snail-mail, gewoon op de brievenbus gedaan dus.</p>
                            <p>Zodra wij het binnen hebben melden wij je, via email, dat we de aanvraag binnen hebben. Daarna gaan we alles doornemen. Allereerst gaan we kijken of de aanvraag compleet is. Zit alle vereiste informatie erbij?
	                            Vervolgens controleren we of de aanvraag aan de voorwaarden voldoet.</p>
	                        <p>Op basis van dit onderzoek krijg je van ons één van de volgende reacties:
		                        <ul>
			                        <li>Je aanvraag is niet compleet, graag ontvangen wij van je aanvullende informatie</li>
			                        <li>Je aanvraag voldoet niet aan de voorwaarden, graag ontvangen wij van je een aangepaste aanvraag</li>
			                        <li>Je aanvraag voldoet niet aan de voorwaarden, deze aanvraag wijzen wij af</li>
			                        <li>Je aanvraag is compleet en voldoet aan de voorwaarden. Wij nemen deze aanvraag in overweging.</li>
		                        </ul>
                            </p>
                            <p>De eerste 2 genoemde reacties kunnen meerdere keren worden gegeven. Uiteindelijk ontvang je één van de laatste 2 reacties.</p>
                            <p>Als je laatstgenoemde reactie krijgt, krijg je daarna een definitief antwoord op je aanvraag:
	                            <ul>
		                            <li>De aanvraag wordt toegewezen</li>
		                            <li>De aanvraag wordt gedeeltelijk toegewezen</li>
		                            <li>De aanvraag wordt afgewezen</li>
	                            </ul>
	                        <p>Na dit antwoord nemen we contact met je op en regelen wij dat alles verloopt zoals het hoort.</p>
	                        <p>Ons streven is om de termijn tussen het indienen van de aanvraag en het geven van een definitief antwoord maximaal 5 weken te laten zijn. 
		                        Uiteraard is dit ook afhankelijk van je eigen reactietijd op onze vragen.</p>
							<button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subject Modal 6 -->
    <div class="subject-modal modal fade" id="subjectModal6" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Wie kunnen je nog meer helpen?</h2>
                            <img class="img-responsive img-centered" src="img/subject/doelgroep.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">Je plan is klaar, je hebt een bijdrage aangevraagd. Wie kunnen je helpen jouw idee te realiseren?</h4>
                            <p>Je hebt, meestal samen met anderen, zorgvuldig nagedacht over wat je wilt gaan doen om de Zoetermeerse samenleving naar een hoger plan te tillen.
	                            Je aanvraag voor een financiële bijdrage van het Zoetermeerfonds is inmiddels ingediend, of wellicht al toegekend. Nu komt het erop aan om je doelen te behalen.
                            </p>
                            <p>Natuurlijk hangt het af van je plannen maar er zijn diverse organisaties in Zoetermeer die je verder kunnen helpen:</p>
	                            <ol>
		                            <li>Het VIP (Vrijwilligers Informatie Punt) is je startpunt als je vrijwilligers zoekt die mee kunnen denken en werken</li>
		                            <li>De Stadsambassade is een club van mensen die zich inzet voor Zoetermeer en zich met name richt op alles rond ruimtelijke ordening</li>
		                            <li>BizKwadraat ondersteunt bugerinitiatieven en organiseert regelmatig informatieve bijeenkomsten</li>
	                            </ol>
	                            <p>Soms heb je meer geld nodig. Dan is het zaak om meer bronnen aan te boren. Je kunt dan terecht bij o.a.</p>
	                            <ol>
		                            <li>Fonds 1818</li>
		                            <li>Het Rabo Coöperatiefonds</li>
		                            <li>Het Oranjefonds</li>
		                            <li>Voor je buurt (crowdfunding)</li>
	                            </ol>
	                        <p>Als je ook bij andere potentiële donateurs aanklopt, meld dan dat je al bij het Zoetermeerfonds bent geweest en vermeld ook wat daarvan het resultaat was.</p>
							<p>Succes!</p>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    

    <!-- subject Modal 11 -->
    <div class="subject-modal modal fade" id="subjectModal11" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Wie zitten er achter het fonds?</h2>
                            <img class="img-responsive img-centered" src="img/subject/achter-de-schermen.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">Het draait allemaal om vertrouwen.</h4>
                            <p>Begin 2014 startte BizKwadraat met het ondersteunen van burgerinitiatieven in Zoetermeer. Deze steun bestaat uit het organiseren van bijeenkomsten voor initiatiefnemers zodat ze met elkaar kennis
	                            kunnen maken en kennis en ervaring kunnen uitwisselen. Daarnaast staat BizKwadraat initiatiefnemers bij met de organisatie en realisatie van hun ideeën en plannen.</p>
	                        <p>De gemeente Zoetermeer hecht groot belang aan de maatschappelijke participatie van haar inwoners en wil burgerinitiatieven zo goed mogelijk stimuleren.</p>
	                        <p>In Nederland zijn steeds meer fondsen actief die op lokaal niveau willen bijdragen aan burgerparticipatie. Om deze fondsen te helpen is Lokale Fondsen Nederland opgericht 
		                        door SBF (Samenwerkende Brancheorganisatie Filantropie ) en het ministerie van Binnenlandse Zaken. 
                            </p>
                            <p>Deze drie partijen hebben de handen ineen geslagen en hebben besloten een speciaal op Zoetermeer gericht lokaal fonds op te richten dat tot doel krijgt lokale initiatieven waar mogelijk financieel maar eventueel ook anderszins te ondersteunen.</p>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subject Modal 12 -->
    <div class="subject-modal modal fade" id="subjectModal12" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Wat gebeurt er met mijn geld?</h2>
<!--                             <p class="item-intro text-muted">Het Zoetermeer&shy;fonds gaat niet over één nacht ijs.</p> -->
                            <img class="img-responsive img-centered" src="img/subject/geld-uitgeven.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">We worden een ANBI-stichting</h4>
                            <p>De stichting is net opgericht. Om onze doelen te borgen en iedereen die ons geld toevertrouwt zoveel mogelijk vertrouwen te geven, heeft het Zoetermeer&shy;fonds de ANBI-status aangevraagd bij de 
	                            belastingdienst. Dit houdt o.a. in dat donaties aan de stichting, onder voorwaarden, aftrekbaar zijn voor de donateur. 
	                            Verder is de stichting verplicht jaarlijks een financieel verslag te publiceren zodat alle betrokken partijen inzage hebben de wijze waarop het geld is besteed.</p>
	                        <p>Zo zijn er nog meer eisen waaraan de stichting moet voldoen. Deze en andere informatie over de ANBI-status kunt u nalezen op <a href="http://www.anbi.nl/" target="_blank">deze website</a>.                                
                            </p>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subject Modal 13 -->
    <div class="subject-modal modal fade" id="subjectModal13" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Hoe kan ik een donatie doen?</h2>
                            <img class="img-responsive img-centered" src="img/subject/doneren.jpg" width="600" alt="">
                            <h4 class="item-intro text-muted">Bijdragen aan Het Zoetermeer&shy;fonds is simpel.</h4>
                            <p>Doneren aan de stichting Zoetermeerfonds is eenvoudig. Uw gift kunt u storten op het rekeningnummer van de stichting dat
	                            onderaan iedere pagina van deze website kunt terugvinden.</p>
	                        <p>Uiteraard kunt u ook eerst met één van de bestuursleden contact opnemen.</p> 
                            <p>In de toekomst willen we op diverse manieren geld inzamelen. Plannen daarvoor zijn nog in ontwikkeling.</p>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 
     <!-- subject Modal 14 -->
    <div class="subject-modal modal fade" id="subjectModal14" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2>Disclaimer</h2>
                            <p class="item-intro text-muted">De informatie die door het Zoetermeerfonds op haar website wordt aangeboden is met grote zorg samengesteld. 
	                                    Het Zoetermeerfonds controleert alle publicaties zeer zorgvuldig, zodat aangeboden informatie zo actueel en nauwkeurig mogelijk is. 
	                                    Ondanks de voortdurende aandacht voor de kwaliteit van haar berichtgeving kan het Zoetermeerfonds niet garanderen dat de informatie op haar website altijd juist, actueel of volledig is. 
	                                    Aan de op de website aangeboden informatie en/of diensten kunnen op geen enkele manier rechten worden ontleend. 
	                                    Het Zoetermeerfonds aanvaardt geen enkele aansprakelijkheid voor eventuele onjuistheden, noch voor informatie op websites waarnaar verwezen wordt. 
	                                    Het Zoetermeerfonds behoudt zich het recht voor om de informatie op haar website te allen tijde te verbeteren of anderszins te wijzigen.
	                                    Mocht u in de berichtgeving op de website van het Zoetermeerfonds onjuistheden signaleren, dan stellen wij het zeer op prijs dat u deze meldt bij de webredactie.</p>
                            <img class="img-responsive img-centered" src="img/subject/doneren.jpg" width="600" alt="">
                            <p>
                                
                            </p>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Sluit venster</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 
    </div>
